---
title: "About me"
description: |
  Education & Research Experience
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Education

**Master of Environmental Science & Management** Bren School of Environmental Science & Management (Expected June 2023) 

- Energy & Climate Specialization

- Corporate Environmental Management Specialization

- Innovation Focus

*Highlighted Coursework:* Financial Management & Environmental Accounting, Energy Demand, Environmental Business, Environmental Economics, Environmental Policy, Data Analysis, Advanced Data Analysis


**B.A. with Honors in Environmental Studies & Anthropology** University of California, Santa Barbara (June 2013)

- Spatial Science Minor

- American Indian and Indigenous Studies Minor

- Senior Honors Thesis: Paleoethnobotanical Analysis of Farming and Food Systems in Central Illinois


## Renewable Energy Procurement & ESG Experience

**Project Manager – Client: Paramount Global; Master’s Group Project** Santa Barbara, CA (3/22- Present) *A Corporate Renewable Energy Procurement Strategy*

- Conducted in-depth analysis of energy consumption and Scope 2 emissions for Paramount's 300+ U.S.       facilities, leveraging data insights to identify priority facilities for procuring renewable energy

- Modeled Scope 2 emissions reductions using on-site solar, PPA, and VPPA financing structures to         evaluate potential monetary costs, benefits, and risks of renewable energy procurement

- Led a team of 6 professionals in project management, facilitating regular team meetings, collaborating   on project tasks, and providing direction throughout the project, from initial work plan development    to final deliverables

**ESG Strategy Intern – Paramount Global** Remote Position (6/22-8/22)

- Conducted internal stakeholder interviews to assess ESG performance and identify areas for              improvement, and provided recommendations to management based on findings

- Reported ESG trends and best practices from Sustainable Production Alliance (SPA) meetings to the       Paramount Global team

- Facilitated high-level meetings with C-suite and steering committee to discuss ESG strategies using     prepared slide deck presentation materials


## Management and Communication Experience

**Lead Teaching Assistant – Environmental Studies Department UCSB** Santa Barbara, CA (9/21-Present)

- Supervised a team of 8 teaching assistants in developing course materials and leading class             discussions

- Facilitated weekly meetings to review course progress and provide feedback on teaching strategies

- Collaborated with the course instructor to create and revise course syllabi, assignments, and exams,    resulting in improved student learning outcomes and increased course satisfaction ratings


**Assistant Manager of Operations – SurePrep LLC** Irvine, CA (1/17–9/21)

- Drove productivity and accuracy of tax data entry and verification operations by closely monitoring     productivity reports and implementing corrective actions to ensure service standards and output goals   were consistently met

- Spearheaded the successful recruitment, onboarding, training, and evaluation of 400+ temporary          employees hired each tax season, resulting in a significant increase in both the quantity and quality   of production

- Developed onboarding and training materials, equipping new hires with the necessary knowledge and       skills to excel and improve performance


**Skills, Certifications, & Activities**

**Computer:** Microsoft Office (Excel, Word, PowerPoint), RStudio, GitHub, Canva
**Presentations:** Bren Public Thesis Presentation – 100+ person audience, Society of Ethnobiology Conference – 300+ person audience, American Anthropological Association – poster presentation
**Certifications:** GHG Accounting – Greenhouse Gas Institute



